//! Prints `crates/guest-sdk/src/phone/metadata.rs` from libphonenumber's metadata (customers#121,
//! moved into the guest SDK by appointments#313).
//!
//! The full library does not fit the hub's WASM sandbox: loading its metadata spends more than
//! the 200M fuel a handler call is given. The handler only needs four facts per country — its
//! calling code, its trunk prefix, the international call prefix dialled from it and the lengths
//! a national number may have — so they are extracted here, once, and compiled in as a table.
//!
//! `cargo run -q` prints the Rust table; `cargo run -q -- sql` prints the same rows as the
//! `VALUES` list Customers' `commands/_phones_to_e164.sql` carries, so the upgrade of the cards
//! that already exist reads the same table as the handler (the battery
//! `tests/phone_e164_backfill.pg.test.py` compares them row by row).

use phonenumber::metadata::DATABASE;

fn main() {
    let mut rows: Vec<(String, u16, String, String, Vec<u16>)> = DATABASE
        .iter()
        .map(|m| {
            // The general descriptor leaves its lengths empty: they are the union of every kind
            // of number the region has (fixed line, mobile, toll free…).
            let d = m.descriptors();
            let mut lengths: Vec<u16> = std::iter::once(Some(d.general()))
                .chain([
                    d.fixed_line(), d.mobile(), d.toll_free(), d.premium_rate(), d.shared_cost(),
                    d.personal_number(), d.voip(), d.pager(), d.uan(), d.voicemail(),
                ])
                .flatten()
                .flat_map(|x| x.possible_length().iter().copied())
                .collect();
            lengths.sort_unstable();
            lengths.dedup();
            let idd = m
                .international_prefix()
                .map(|r| r.as_str().to_string())
                .filter(|p| !p.is_empty() && p.chars().all(|c| c.is_ascii_digit()))
                .or_else(|| m.preferred_international_prefix().map(str::to_string))
                .filter(|p| p.chars().all(|c| c.is_ascii_digit()))
                .unwrap_or_default();
            (
                m.id().to_string(),
                m.country_code(),
                m.national_prefix().unwrap_or("").to_string(),
                idd,
                lengths,
            )
        })
        .collect();
    rows.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)));

    if std::env::args().nth(1).as_deref() == Some("sql") {
        let last = rows.len().saturating_sub(1);
        for (i, (iso, code, trunk, idd, lengths)) in rows.iter().enumerate() {
            let l: Vec<String> = lengths.iter().map(|n| n.to_string()).collect();
            let sep = if i == last { "" } else { "," };
            println!("    ('{iso}', '{code}', '{trunk}', '{idd}', '{{{}}}'::int[]){sep}", l.join(","));
        }
        return;
    }

    println!("//! GENERATED by `crates/guest-sdk/tools/phone-metadata` from libphonenumber 9.0.33 (crate `phonenumber` 0.3.10).");
    println!("//! Do not edit by hand: regenerate (customers#121, appointments#313). One row per region: ISO 3166 id (`001` for the");
    println!("//! non-geographic codes), calling code, trunk prefix, international call prefix and possible");
    println!("//! national number lengths.");
    println!();
    println!("pub struct Region {{");
    println!("    pub iso: &'static str,");
    println!("    pub code: &'static str,");
    println!("    pub trunk: &'static str,");
    println!("    pub idd: &'static str,");
    println!("    pub lengths: &'static [u8],");
    println!("}}");
    println!();
    println!("pub const REGIONS: &[Region] = &[");
    for (iso, code, trunk, idd, lengths) in rows {
        let l: Vec<String> = lengths.iter().map(|n| n.to_string()).collect();
        println!(
            "    Region {{ iso: \"{iso}\", code: \"{code}\", trunk: \"{trunk}\", idd: \"{idd}\", lengths: &[{}] }},",
            l.join(", ")
        );
    }
    println!("];");
}
