"""
PWA Icon Service

Provides URL helpers for PWA icons stored in media/pwa_icons/.
Icons are generated by:
- AWS Lambda (web deployment) — triggered via SQS from signals.py
- Pillow locally (development) — called directly from signals.py

This module handles reading/checking icons and local generation as fallback.
"""
import io
import logging

from django.core.files.base import ContentFile
from django.core.files.storage import default_storage

logger = logging.getLogger(__name__)

# Required PWA icon sizes
PWA_ICON_SIZES = [72, 96, 128, 144, 152, 192, 384, 512]

# Favicon sizes
FAVICON_SIZES = [16, 32, 48]

# Directory within MEDIA for generated icons
PWA_ICONS_DIR = 'pwa_icons'


# ---------------------------------------------------------------------------
# Read helpers (used by manifest view + templates)
# ---------------------------------------------------------------------------

def pwa_icons_exist():
    """Check if custom PWA icons have been generated (checks 192px icon)."""
    return default_storage.exists(f'{PWA_ICONS_DIR}/icon-192x192.png')


def get_icon_urls():
    """
    Get URLs for all PWA icon sizes for the manifest.

    Returns:
        List of dicts with src, sizes, type, purpose keys.
        Returns None if no custom icons exist.
    """
    if not pwa_icons_exist():
        return None

    icons = []
    for size in PWA_ICON_SIZES:
        path = f'{PWA_ICONS_DIR}/icon-{size}x{size}.png'
        url = default_storage.url(path)
        icon = {
            'src': url,
            'sizes': f'{size}x{size}',
            'type': 'image/png',
        }
        # Maskable icons for Android adaptive icons (192 and 512)
        if size in (192, 512):
            icon['purpose'] = 'any maskable'
        icons.append(icon)

    return icons


def get_favicon_url(size=32):
    """Get URL for the custom favicon, or None."""
    path = f'{PWA_ICONS_DIR}/favicon-{size}.png'
    if default_storage.exists(path):
        return default_storage.url(path)
    return None


def get_apple_touch_icon_url():
    """Get URL for the Apple touch icon (152px), or None."""
    path = f'{PWA_ICONS_DIR}/icon-152x152.png'
    if default_storage.exists(path):
        return default_storage.url(path)
    return None


def delete_pwa_icons():
    """Remove all generated PWA icons from storage."""
    try:
        for size in PWA_ICON_SIZES:
            path = f'{PWA_ICONS_DIR}/icon-{size}x{size}.png'
            if default_storage.exists(path):
                default_storage.delete(path)

        for size in FAVICON_SIZES:
            path = f'{PWA_ICONS_DIR}/favicon-{size}.png'
            if default_storage.exists(path):
                default_storage.delete(path)

        logger.info('PWA icons deleted')
    except Exception:
        logger.exception('Failed to delete PWA icons')


# ---------------------------------------------------------------------------
# Local generation (development fallback — requires Pillow)
# ---------------------------------------------------------------------------

def generate_pwa_icons(logo_field):
    """
    Generate all PWA icon sizes locally using Pillow.
    Used in development mode only. In production, Lambda handles this.

    Args:
        logo_field: Django ImageField instance (StoreConfig.logo)

    Returns:
        True if icons were generated successfully, False otherwise.
    """
    try:
        from PIL import Image
    except ImportError:
        logger.warning('Pillow not installed, cannot generate PWA icons locally')
        return False

    if not logo_field:
        return False

    try:
        logo_field.seek(0)
        img = Image.open(logo_field)
        img = img.convert('RGBA')

        for size in PWA_ICON_SIZES:
            _save_icon(img, size)

        for size in FAVICON_SIZES:
            _save_favicon_size(img, size)

        logger.info('PWA icons generated locally (%d icons + %d favicons)',
                     len(PWA_ICON_SIZES), len(FAVICON_SIZES))
        return True

    except Exception:
        logger.exception('Failed to generate PWA icons locally')
        return False


def _save_icon(img, size):
    """Resize image to square icon with padding and save to storage."""
    from PIL import Image as PILImage

    canvas = PILImage.new('RGBA', (size, size), (255, 255, 255, 0))
    padded_size = int(size * 0.80)
    resized = img.copy()
    resized.thumbnail((padded_size, padded_size), PILImage.LANCZOS)

    x = (size - resized.width) // 2
    y = (size - resized.height) // 2
    canvas.paste(resized, (x, y), resized if resized.mode == 'RGBA' else None)

    final = PILImage.new('RGB', (size, size), (255, 255, 255))
    final.paste(canvas, mask=canvas.split()[3])

    buf = io.BytesIO()
    final.save(buf, format='PNG', optimize=True)

    path = f'{PWA_ICONS_DIR}/icon-{size}x{size}.png'
    if default_storage.exists(path):
        default_storage.delete(path)
    default_storage.save(path, ContentFile(buf.getvalue()))


def _save_favicon_size(img, size):
    """Generate a single favicon PNG."""
    from PIL import Image as PILImage

    resized = img.copy()
    resized.thumbnail((size, size), PILImage.LANCZOS)

    canvas = PILImage.new('RGBA', (size, size), (255, 255, 255, 0))
    x = (size - resized.width) // 2
    y = (size - resized.height) // 2
    canvas.paste(resized, (x, y), resized if resized.mode == 'RGBA' else None)

    final = PILImage.new('RGB', (size, size), (255, 255, 255))
    final.paste(canvas, mask=canvas.split()[3])

    buf = io.BytesIO()
    final.save(buf, format='PNG', optimize=True)

    path = f'{PWA_ICONS_DIR}/favicon-{size}.png'
    if default_storage.exists(path):
        default_storage.delete(path)
    default_storage.save(path, ContentFile(buf.getvalue()))
