# Generated by Django 5.2.8 on 2025-12-16 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('cloud_user_id', models.IntegerField(blank=True, help_text='Cloud user ID. NULL = local-only employee (PIN auth only)', null=True)),
                ('email', models.EmailField(help_text='User email (unique per Hub)', max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('pin_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Local User',
                'verbose_name_plural': 'Local Users',
                'db_table': 'accounts_localuser',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['hub_id', 'is_active'], name='accounts_lo_hub_id_30cc07_idx'), models.Index(fields=['hub_id', 'role'], name='accounts_lo_hub_id_2ec9da_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hub_id', 'email'), name='unique_email_per_hub'), models.UniqueConstraint(condition=models.Q(('cloud_user_id__isnull', False), ('is_deleted', False)), fields=('hub_id', 'cloud_user_id'), name='unique_cloud_user_per_hub')],
            },
        ),
    ]
