# Generated by Django 6.0.1 on 2026-02-09 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Role name (e.g., 'admin', 'manager', 'cashier')", max_length=50)),
                ('display_name', models.CharField(help_text='Human-readable name for UI', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted (admin, manager, employee)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive roles cannot be assigned to users')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'accounts_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('codename', models.CharField(help_text="Permission codename (e.g., 'inventory.view_product')", max_length=100)),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows')),
                ('module_id', models.CharField(help_text='Module that defines this permission', max_length=50)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'accounts_permissions',
                'ordering': ['module_id', 'codename'],
                'indexes': [models.Index(fields=['hub_id', 'module_id'], name='accounts_pe_hub_id_b315f5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hub_id', 'codename'), name='unique_permission_codename_per_hub')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('wildcard', models.CharField(blank=True, help_text="Wildcard pattern (e.g., '*', 'inventory.*')", max_length=100)),
                ('permission', models.ForeignKey(blank=True, help_text='Direct permission link (null if using wildcard)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'accounts_role_permissions',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='accounts.RolePermission', to='accounts.permission'),
        ),
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('cloud_user_id', models.IntegerField(blank=True, help_text='Cloud user ID. NULL = local-only employee (PIN auth only)', null=True)),
                ('email', models.EmailField(help_text='User email (unique per Hub)', max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('pin_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('extra_permissions', models.ManyToManyField(blank=True, help_text='Additional permissions beyond role (for special cases)', related_name='users_extra', to='accounts.permission')),
                ('role_obj', models.ForeignKey(blank=True, help_text="Role object for granular permissions. If null, uses legacy 'role' field.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Local User',
                'verbose_name_plural': 'Local Users',
                'db_table': 'accounts_local_users',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['hub_id', 'is_active'], name='accounts_lo_hub_id_8ac67d_idx'), models.Index(fields=['hub_id', 'role'], name='accounts_lo_hub_id_ba0ae0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hub_id', 'email'), name='unique_email_per_hub'), models.UniqueConstraint(condition=models.Q(('cloud_user_id__isnull', False), ('is_deleted', False)), fields=('hub_id', 'cloud_user_id'), name='unique_cloud_user_per_hub')],
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('permission__isnull', False)), fields=('hub_id', 'role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('wildcard__gt', '')), fields=('hub_id', 'role', 'wildcard'), name='unique_role_wildcard'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hub_id', 'name'), name='unique_role_name_per_hub'),
        ),
    ]
