# Generated by Django 5.2.8 on 2025-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='cloud_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
