# Generated by Django 6.0.1 on 2026-02-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('accountant', 'Accountant'), ('warehouse', 'Warehouse'), ('cashier', 'Cashier'), ('viewer', 'Viewer')], default='employee', max_length=20),
        ),
    ]
