# Generated by Django 5.2.8 on 2025-12-15 21:53

from django.db import migrations, models


def migrate_old_roles(apps, schema_editor):
    """
    Convert old roles (cashier, seller) to new role (employee).
    admin and manager remain unchanged.
    """
    LocalUser = apps.get_model('accounts', 'LocalUser')
    # Map old roles to new roles
    LocalUser.objects.filter(role__in=['cashier', 'seller']).update(role='employee')


def reverse_migrate_roles(apps, schema_editor):
    """
    Reverse migration: convert employee back to cashier.
    This is a lossy operation (seller becomes cashier).
    """
    LocalUser = apps.get_model('accounts', 'LocalUser')
    LocalUser.objects.filter(role='employee').update(role='cashier')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_make_cloud_user_id_nullable'),
    ]

    operations = [
        # First migrate the data
        migrations.RunPython(migrate_old_roles, reverse_migrate_roles),
        # Then alter the field
        migrations.AlterField(
            model_name='localuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
