# Generated by Django 6.0.1 on 2026-02-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_localuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='source',
            field=models.CharField(choices=[('basic', 'Basic'), ('solution', 'Solution'), ('custom', 'Custom')], default='custom', help_text='Origin: basic (always active), solution (from selected solution), custom (user-created)', max_length=20),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('viewer', 'Viewer')], default='employee', max_length=20),
        ),
    ]
