# Generated by Django 5.2.8 on 2025-12-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='cloud_user_id',
            field=models.IntegerField(blank=True, help_text='Cloud user ID. NULL = local-only employee (PIN auth only)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='email',
            field=models.EmailField(help_text='Unique identifier', max_length=254, unique=True),
        ),
    ]
