/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ErpCashregisterDashboard {
    }
    interface ErpCustomersList {
    }
    interface ErpInventoryProducts {
    }
    interface ErpInvoiceList {
    }
    interface ErpSalesList {
    }
}
declare global {
    interface HTMLErpCashregisterDashboardElement extends Components.ErpCashregisterDashboard, HTMLStencilElement {
    }
    var HTMLErpCashregisterDashboardElement: {
        prototype: HTMLErpCashregisterDashboardElement;
        new (): HTMLErpCashregisterDashboardElement;
    };
    interface HTMLErpCustomersListElement extends Components.ErpCustomersList, HTMLStencilElement {
    }
    var HTMLErpCustomersListElement: {
        prototype: HTMLErpCustomersListElement;
        new (): HTMLErpCustomersListElement;
    };
    interface HTMLErpInventoryProductsElement extends Components.ErpInventoryProducts, HTMLStencilElement {
    }
    var HTMLErpInventoryProductsElement: {
        prototype: HTMLErpInventoryProductsElement;
        new (): HTMLErpInventoryProductsElement;
    };
    interface HTMLErpInvoiceListElement extends Components.ErpInvoiceList, HTMLStencilElement {
    }
    var HTMLErpInvoiceListElement: {
        prototype: HTMLErpInvoiceListElement;
        new (): HTMLErpInvoiceListElement;
    };
    interface HTMLErpSalesListElement extends Components.ErpSalesList, HTMLStencilElement {
    }
    var HTMLErpSalesListElement: {
        prototype: HTMLErpSalesListElement;
        new (): HTMLErpSalesListElement;
    };
    interface HTMLElementTagNameMap {
        "erp-cashregister-dashboard": HTMLErpCashregisterDashboardElement;
        "erp-customers-list": HTMLErpCustomersListElement;
        "erp-inventory-products": HTMLErpInventoryProductsElement;
        "erp-invoice-list": HTMLErpInvoiceListElement;
        "erp-sales-list": HTMLErpSalesListElement;
    }
}
declare namespace LocalJSX {
    interface ErpCashregisterDashboard {
    }
    interface ErpCustomersList {
    }
    interface ErpInventoryProducts {
    }
    interface ErpInvoiceList {
    }
    interface ErpSalesList {
    }
    interface IntrinsicElements {
        "erp-cashregister-dashboard": ErpCashregisterDashboard;
        "erp-customers-list": ErpCustomersList;
        "erp-inventory-products": ErpInventoryProducts;
        "erp-invoice-list": ErpInvoiceList;
        "erp-sales-list": ErpSalesList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "erp-cashregister-dashboard": LocalJSX.IntrinsicElements["erp-cashregister-dashboard"] & JSXBase.HTMLAttributes<HTMLErpCashregisterDashboardElement>;
            "erp-customers-list": LocalJSX.IntrinsicElements["erp-customers-list"] & JSXBase.HTMLAttributes<HTMLErpCustomersListElement>;
            "erp-inventory-products": LocalJSX.IntrinsicElements["erp-inventory-products"] & JSXBase.HTMLAttributes<HTMLErpInventoryProductsElement>;
            "erp-invoice-list": LocalJSX.IntrinsicElements["erp-invoice-list"] & JSXBase.HTMLAttributes<HTMLErpInvoiceListElement>;
            "erp-sales-list": LocalJSX.IntrinsicElements["erp-sales-list"] & JSXBase.HTMLAttributes<HTMLErpSalesListElement>;
        }
    }
}
