# Generated by Django 5.2.7 on 2025-11-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('install_path', models.CharField(blank=True, max_length=500)),
                ('is_installed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('icon', models.CharField(default='cube-outline', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('menu_label', models.CharField(blank=True, max_length=100)),
                ('menu_icon', models.CharField(blank=True, max_length=50)),
                ('menu_order', models.IntegerField(default=100)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('main_url', models.CharField(blank=True, max_length=200)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
                'db_table': 'plugins_admin_plugin',
                'ordering': ['menu_order', 'name'],
            },
        ),
    ]
