//! Guard for the shell's COMMAND SURFACE and for what ADR-0154 took out of it (hub#336).
//!
//! ADR-0154 turned the product cloud-first: the hub runs in production, the shell is a thin client
//! (ADR-0159) and the webview talks HTTP+WS to a REMOTE hub. Three things died with that pivot and
//! are already gone from the code — the embedded runtime (`erplora_server::serve` on loopback
//! `:8787` plus its local SQLite), the `validate_entitlement` invoke (an offline RS256 gate with a
//! cached token and a grace window), and `frontendDist` pointing at the hub web app's `dist/`.
//!
//! This file is what stops them from coming back, and what keeps the pieces that survived
//! agreeing with each other. Nothing here re-tests the hardware handlers: those ARE the reason the
//! app exists and are deliberately untouched.
//!
//! ## Why the command surface needs a test at all
//!
//! Four artifacts describe the same list of commands, and each is written by a different hand:
//!
//! | Artifact | Written by | What it does |
//! | --- | --- | --- |
//! | `build.rs` → `AppManifest::commands` | us | makes `tauri-build` emit an `allow-<cmd>` permission |
//! | `permissions/autogenerated/*.toml` | `tauri-build` | the emitted permissions, committed |
//! | `src/lib.rs` → `generate_handler!` | us | the commands that actually EXIST |
//! | `capabilities/*.json` | us | which origin is granted which `allow-<cmd>` |
//!
//! `build.rs` asks, in a comment, that the first be kept "in sync" with the third. A comment is
//! not a guard, and drifting either way fails SILENTLY in opposite directions:
//!
//! - **declared but not handled** — a permission is generated and handed to an origin for a
//!   command that does not exist. Dead grant surface. This is exactly what `validate_entitlement`
//!   was: still registered in `build.rs` long after the gate itself was deleted.
//! - **handled but not declared** — no `allow-<cmd>` exists, so Tauri's ACL refuses the command
//!   from every remote origin. **Dev does not show this**: a local origin with no app manifest
//!   skips the gate, so it works on the laptop and the till simply never prints.
//!
//! The second one is the expensive one, and it is invisible until a real hub is in front of you.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(relative: &str) -> String {
    let path = manifest_dir().join(relative);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
}

/// Drops `//` line comments so a command named inside prose is never mistaken for a declaration.
/// Both lists we parse carry explanatory comments between their entries.
fn without_line_comments(source: &str) -> String {
    source
        .lines()
        .map(|line| match line.find("//") {
            Some(at) => &line[..at],
            None => line,
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// The slice between `opening` and the first `]` after it. Both lists hold flat entries (string
/// literals or bare identifiers), so the first bracket is the closing one.
fn bracketed_block<'a>(source: &'a str, opening: &str, what: &str) -> &'a str {
    let start = source
        .find(opening)
        .unwrap_or_else(|| panic!("{what}: `{opening}` not found — did the declaration move?"))
        + opening.len();
    let rest = &source[start..];
    let end = rest
        .find(']')
        .unwrap_or_else(|| panic!("{what}: `{opening}` is never closed"));
    &rest[..end]
}

/// Commands declared to `tauri-build` in `build.rs`. These are what become `allow-<cmd>`.
fn commands_declared_to_the_build() -> BTreeSet<String> {
    let source = read("build.rs");
    let block = bracketed_block(&source, "commands(&[", "build.rs");
    let block = without_line_comments(block);

    let mut found = BTreeSet::new();
    let mut rest = block.as_str();
    while let Some(open) = rest.find('"') {
        rest = &rest[open + 1..];
        let close = rest
            .find('"')
            .expect("build.rs: unterminated string literal in the command list");
        found.insert(rest[..close].to_string());
        rest = &rest[close + 1..];
    }

    assert!(
        !found.is_empty(),
        "build.rs declares no command: every invoke from a remote origin would be refused"
    );
    found
}

/// Commands that actually exist, as handed to `tauri::generate_handler!` in `lib.rs`.
fn commands_wired_to_the_handler() -> BTreeSet<String> {
    let source = read("src/lib.rs");
    let block = bracketed_block(&source, "generate_handler![", "src/lib.rs");
    let block = without_line_comments(block);

    let found: BTreeSet<String> = block
        .split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(str::to_string)
        .collect();

    assert!(
        !found.is_empty(),
        "lib.rs wires no command: the app would expose no IPC at all"
    );
    found
}

/// Commands covered by a committed `permissions/autogenerated/*.toml`. Read from the `commands.allow`
/// line rather than the file name: the file name is a convention, the line is the contract.
fn commands_with_a_generated_permission() -> BTreeSet<String> {
    let dir = manifest_dir().join("permissions/autogenerated");
    let mut found = BTreeSet::new();

    let entries = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|entry| entry.expect("cannot read permission entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "toml"));

    for path in entries {
        let raw = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        for line in raw.lines() {
            let line = line.trim();
            let Some(list) = line.strip_prefix("commands.allow") else {
                continue;
            };
            let Some(list) = list.trim_start().strip_prefix('=') else {
                continue;
            };
            for chunk in list.split('"').skip(1).step_by(2) {
                found.insert(chunk.to_string());
            }
        }
    }

    assert!(
        !found.is_empty(),
        "no permission committed in {}: the ACL would grant nothing",
        dir.display()
    );
    found
}

/// Every `allow-<cmd>` a capability hands out, back in command spelling. Namespaced permissions
/// (`core:default`, `erplora-android:default`) belong to Tauri and to the Android plugin, not to
/// this crate's command list, so they are out.
fn command_permissions_granted_by_capabilities() -> BTreeSet<(String, String)> {
    let dir = manifest_dir().join("capabilities");
    let mut granted = BTreeSet::new();

    let entries = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|entry| entry.expect("cannot read capability entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"));

    for path in entries {
        let file = format!(
            "capabilities/{}",
            path.file_name().unwrap_or_default().to_string_lossy()
        );
        let raw = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        let json: serde_json::Value = serde_json::from_str(&raw)
            .unwrap_or_else(|e| panic!("{file} is not valid JSON: {e}"));

        for permission in json["permissions"]
            .as_array()
            .unwrap_or_else(|| panic!("{file} must declare permissions as an array"))
        {
            let permission = permission
                .as_str()
                .unwrap_or_else(|| panic!("{file}: every permission must be a string"));
            if permission.contains(':') {
                continue;
            }
            let Some(command) = permission.strip_prefix("allow-") else {
                continue;
            };
            // `tauri-build` spells permissions in kebab-case; the commands are snake_case.
            granted.insert((file.clone(), command.replace('-', "_")));
        }
    }

    granted
}

fn tauri_config() -> serde_json::Value {
    let raw = read("tauri.conf.json");
    serde_json::from_str(&raw).expect("tauri.conf.json is not valid JSON")
}

/// Direct dependencies of the crate, i.e. the `[dependencies]` table. Target-specific and dev
/// tables are deliberately out: what matters here is what the SHIPPED shell links.
fn direct_dependencies() -> BTreeSet<String> {
    let source = read("Cargo.toml");
    let mut deps = BTreeSet::new();
    let mut inside = false;

    for line in source.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            inside = line == "[dependencies]";
            continue;
        }
        if !inside || line.starts_with('#') || line.is_empty() {
            continue;
        }
        if let Some((name, _)) = line.split_once('=') {
            deps.insert(name.trim().to_string());
        }
    }

    assert!(
        deps.contains("tauri"),
        "parsed no dependency table — the guard below would pass vacuously"
    );
    deps
}

fn rust_sources(dir: &Path, into: &mut Vec<(String, String)>) {
    for entry in std::fs::read_dir(dir).unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display())) {
        let path = entry.expect("cannot read source entry").path();
        if path.is_dir() {
            rust_sources(&path, into);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            let raw = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
            into.push((path.display().to_string(), raw));
        }
    }
}

// ── The command surface agrees with itself ───────────────────────────────────────────────────────

#[test]
fn the_build_manifest_and_the_invoke_handler_declare_the_same_commands() {
    let declared = commands_declared_to_the_build();
    let wired = commands_wired_to_the_handler();

    let declared_but_missing: Vec<_> = declared.difference(&wired).collect();
    assert!(
        declared_but_missing.is_empty(),
        "build.rs declares commands that lib.rs does not implement: {declared_but_missing:?}.\n\
         Each one makes `tauri-build` emit an `allow-<cmd>` permission for a command that does not \
         exist, so a capability can hand an origin a grant that leads nowhere. This is how \
         `validate_entitlement` outlived its own gate (ADR-0154, hub#336)."
    );

    let wired_but_undeclared: Vec<_> = wired.difference(&declared).collect();
    assert!(
        wired_but_undeclared.is_empty(),
        "lib.rs wires commands that build.rs does not declare: {wired_but_undeclared:?}.\n\
         Without an `allow-<cmd>` permission Tauri's ACL refuses the command from EVERY remote \
         origin, and the shell only ever loads remote origins (ADR-0159). Dev hides it — a local \
         origin with no app manifest skips the gate — so this ships green and the till never prints."
    );
}

#[test]
fn every_declared_command_has_its_autogenerated_permission() {
    let declared = commands_declared_to_the_build();
    let generated = commands_with_a_generated_permission();

    assert_eq!(
        declared, generated,
        "the committed `permissions/autogenerated/` no longer matches `build.rs`.\n\
         These files are build OUTPUT that lives in git: a command added to build.rs without \
         re-running the build has no permission to grant, and a permission left behind for a \
         REMOVED command keeps a dead grant alive in the ACL. Re-run the build and commit the diff."
    );
}

#[test]
fn every_command_permission_a_capability_grants_exists() {
    let declared = commands_declared_to_the_build();

    for (file, command) in command_permissions_granted_by_capabilities() {
        assert!(
            declared.contains(&command),
            "{file} grants `allow-{}` but no such command is declared in build.rs.\n\
             A capability is a security boundary; a grant that maps to nothing is not harmless, it \
             is a leftover that outlives the code it was written for.",
            command.replace('_', "-")
        );
    }
}

// ── What ADR-0154 removed stays removed ──────────────────────────────────────────────────────────

#[test]
fn the_shell_declares_no_entitlement_or_device_enrollment_command() {
    // The gate that ADR-0154 deleted, by the names it went under. Entitlement is NOT gone from the
    // product — it moved to where the truth already was: the runtime revalidates paid modules
    // against the Cloud (`crates/server/src/entitlement.rs`, ADR-0114 §6) and the web app resolves
    // it over HTTP (`apps/web/src/lib/entitlement.ts`). What died is the shell's OWN copy: an
    // offline RS256 check over a token cached in `app_data_dir` with a grace window. A thin client
    // that re-decides entitlement locally is a second, weaker answer to a question the Cloud
    // already answers — and the weaker answer is the one an attacker gets to edit on disk.
    let forbidden = [
        "validate_entitlement",
        "enroll_device",
        "rotate_machine_token",
    ];

    let declared = commands_declared_to_the_build();
    let wired = commands_wired_to_the_handler();

    for command in forbidden {
        assert!(
            !declared.contains(command),
            "build.rs declares `{command}`, which ADR-0154 removed from the shell (hub#336). \
             Entitlement is decided by the Cloud and enforced by the runtime, not re-litigated \
             inside the till."
        );
        assert!(
            !wired.contains(command),
            "lib.rs wires `{command}`, which ADR-0154 removed from the shell (hub#336)."
        );
    }
}

#[test]
fn the_shell_does_not_link_the_hub_runtime_or_its_database() {
    // ADR-0154/0159: the hub runs in the cloud and the webview reaches it over HTTP+WS. The shell
    // linking the runtime would mean a second hub — with its own database and its own migrations —
    // living inside the till, which is the local product that the pivot retired.
    let forbidden = [
        ("erplora-server", "the hub runtime (Axum on loopback :8787)"),
        ("erplora-runtime", "the module dispatcher"),
        ("erplora-db", "the hub database layer"),
        ("erplora-installer", "the module installer"),
        ("erplora-cloud-client", "the offline entitlement verifier"),
        ("sqlx", "a SQL driver"),
        ("rusqlite", "the local SQLite database"),
        ("axum", "an HTTP server"),
    ];

    let deps = direct_dependencies();
    for (crate_name, what) in forbidden {
        assert!(
            !deps.contains(crate_name),
            "apps/tauri depends on `{crate_name}` ({what}). The shell is a THIN client (ADR-0159): \
             it renders a remote hub and drives local hardware. Embedding the runtime brings back \
             the local product ADR-0154 retired."
        );
    }

    // The dependency table is the contract, but a path `use` would be the smoking gun.
    let mut sources = Vec::new();
    rust_sources(&manifest_dir().join("src"), &mut sources);
    assert!(
        !sources.is_empty(),
        "no Rust source found under src/ — this guard would pass vacuously"
    );
    for (file, raw) in sources {
        for symbol in ["erplora_server", "erplora_db", "erplora_cloud_client"] {
            assert!(
                !raw.contains(symbol),
                "{file} references `{symbol}`: the embedded runtime is back in the shell (hub#336)."
            );
        }
    }
}

#[test]
fn the_bundle_ships_the_shell_fallback_page_not_the_hub_web_app() {
    // `frontendDist` used to point at `../../web/dist`, i.e. the whole hub PWA was baked into the
    // installer. Under ADR-0154 the PWA is served BY THE HUB, so a baked copy is a second, stale
    // frontend that ships on a release cadence instead of the hub's. What stays bundled is the
    // small degraded page the window falls back to when there is no hub to load yet.
    let config = tauri_config();
    let declared = config["build"]["frontendDist"]
        .as_str()
        .expect("tauri.conf.json must declare build.frontendDist");

    assert_eq!(
        declared, "../shell-dist",
        "frontendDist must stay the shell's own fallback page. Pointing it back at the hub web \
         app bakes a stale copy of the PWA into every installer (ADR-0154, hub#336)."
    );

    let resolved = manifest_dir().join(declared);
    assert!(
        resolved.join("index.html").is_file(),
        "{} has no index.html: the bundle would ship an empty frontend and the degraded page \
         would be a blank window",
        resolved.display()
    );

    // Belt and braces: whatever the path is spelled as, it must not resolve into the web workspace.
    let canonical = resolved
        .canonicalize()
        .unwrap_or_else(|e| panic!("cannot resolve {}: {e}", resolved.display()));
    let canonical = canonical.display().to_string().replace('\\', "/");
    assert!(
        !canonical.contains("/apps/web/"),
        "frontendDist resolves into the hub web app ({canonical}): the installer would bundle the \
         PWA again (ADR-0154, hub#336)."
    );

    // The page is committed, not generated. A build step that produces it from the web workspace
    // is the same resurrection wearing a different hat.
    if let Some(before) = config["build"]["beforeBuildCommand"].as_str() {
        assert!(
            !before.contains("@erplora/web"),
            "beforeBuildCommand builds the hub web app ({before:?}): the bundle would ship the PWA \
             again (ADR-0154, hub#336)."
        );
    }
}
