# Generated by Django 6.0.2 on 2026-03-10 23:41

import apps.core.models.media
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=apps.core.models.media.media_upload_to)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('folder', models.CharField(blank=True, db_index=True, default='', help_text='Folder for organization (e.g., "products", "staff")', max_length=100)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_mediafile',
                'ordering': ['-created_at'],
            },
        ),
    ]
