# Generated by Django 5.2.7 on 2025-11-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='os_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='localuser',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
