# Generated by Django 5.2.7 on 2025-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hubconfig_os_language_localuser_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='extension-puzzle-outline', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_installed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('install_path', models.CharField(blank=True, max_length=500)),
                ('menu_label', models.CharField(blank=True, max_length=100)),
                ('menu_icon', models.CharField(blank=True, max_length=50)),
                ('menu_order', models.IntegerField(default=100)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('main_url', models.CharField(blank=True, max_length=200)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
                'ordering': ['menu_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='VAT/Tax ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate in percentage (e.g., 21.00 for 21%)', max_digits=5)),
                ('tax_included', models.BooleanField(default=True, help_text='Tax included in prices')),
                ('receipt_header', models.TextField(blank=True, help_text='Additional text to show at the top of receipts')),
                ('receipt_footer', models.TextField(blank=True, help_text='Additional text to show at the bottom of receipts')),
                ('is_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
            },
        ),
    ]
