# Generated by Django 5.2.7 on 2025-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_syncqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_access_token', models.TextField(blank=True)),
                ('jwt_refresh_token', models.TextField(blank=True)),
                ('jwt_cached_at', models.DateTimeField(blank=True, null=True)),
                ('rsa_public_key', models.TextField(blank=True)),
                ('public_key_cached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Cache',
                'verbose_name_plural': 'Token Cache',
            },
        ),
    ]
