# Generated by Django 5.2.7 on 2025-11-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tokencache'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='auto_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='color_theme',
            field=models.CharField(choices=[('default', 'Default (Gray)'), ('blue', 'Blue')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
