# Generated by Django 5.2.7 on 2025-11-11 16:36
# Modified: Use SeparateDatabaseAndState to only update Django state,
# without dropping tables (they are moved to other apps)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hubconfig_currency'),
    ]

    operations = [
        # Only remove from Django state, DO NOT drop tables
        # Tables are kept and managed by their new apps:
        # - LocalUser -> accounts app (db_table='core_localuser')
        # - HubConfig, StoreConfig -> configuration app
        # - Plugin -> plugins_admin app
        # - SyncQueue, TokenCache -> sync app
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='HubConfig'),
                migrations.DeleteModel(name='LocalUser'),
                migrations.DeleteModel(name='Plugin'),
                migrations.DeleteModel(name='StoreConfig'),
                migrations.DeleteModel(name='SyncQueue'),
                migrations.DeleteModel(name='TokenCache'),
            ],
            database_operations=[
                # No database operations - tables are kept
            ],
        ),
    ]
