# Generated by Django 5.2.7 on 2025-11-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hubconfig_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HubConfig',
        ),
        migrations.DeleteModel(
            name='LocalUser',
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
        migrations.DeleteModel(
            name='StoreConfig',
        ),
        migrations.DeleteModel(
            name='SyncQueue',
        ),
        migrations.DeleteModel(
            name='TokenCache',
        ),
    ]
