# Generated by Django 6.0.2 on 2026-03-12 22:42

import apps.configuration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable automatic backups')),
                ('frequency', models.CharField(choices=[('disabled', 'Disabled'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often to run backups', max_length=20)),
                ('time_hour', models.PositiveSmallIntegerField(default=3, help_text='Hour to run backup (0-23, default 3 AM)')),
                ('time_minute', models.PositiveSmallIntegerField(default=0, help_text='Minute to run backup (0-59)')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Days to keep backups (0 = keep forever)')),
                ('max_backups', models.PositiveIntegerField(default=10, help_text='Maximum number of backups to keep (0 = unlimited)')),
                ('last_backup_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful backup', null=True)),
                ('last_backup_size', models.PositiveIntegerField(default=0, help_text='Size of last backup in bytes')),
                ('last_backup_path', models.CharField(blank=True, help_text='Path/key of last backup', max_length=500)),
                ('last_error', models.TextField(blank=True, help_text='Last backup error message (empty if successful)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configuration',
                'db_table': 'core_backupconfig',
            },
            bases=(apps.configuration.models.SingletonConfigMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('cloud_api_token', models.TextField(blank=True, help_text='Legacy token (deprecated, use hub_jwt instead)')),
                ('hub_jwt', models.TextField(blank=True, help_text='JWT token for Hub-to-Cloud authentication (RS256, 1 year)')),
                ('hub_refresh_token', models.TextField(blank=True, help_text='Refresh token for Hub JWT (RS256, 2 years)')),
                ('cloud_public_key', models.TextField(blank=True, help_text='Cloud RSA public key for validating command JWTs')),
                ('is_configured', models.BooleanField(default=False)),
                ('os_language', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(choices=[('ADP', 'Andorran Peseta'), ('AED', 'United Arab Emirates Dirham'), ('AFA', 'Afghan Afghani (1927–2002)'), ('AFN', 'Afghan Afghani'), ('ALK', 'Albanian Lek (1946–1965)'), ('ALL', 'Albanian Lek'), ('AMD', 'Armenian Dram'), ('ANG', 'Netherlands Antillean Guilder'), ('AOA', 'Angolan Kwanza'), ('AOK', 'Angolan Kwanza (1977–1991)'), ('AON', 'Angolan New Kwanza (1990–2000)'), ('AOR', 'Angolan Readjusted Kwanza (1995–1999)'), ('ARA', 'Argentine Austral'), ('ARL', 'Argentine Peso Ley (1970–1983)'), ('ARM', 'Argentine Peso (1881–1970)'), ('ARP', 'Argentine Peso (1983–1985)'), ('ARS', 'Argentine Peso'), ('ATS', 'Austrian Schilling'), ('AUD', 'Australian Dollar'), ('AWG', 'Aruban Florin'), ('AZM', 'Azerbaijani Manat (1993–2006)'), ('AZN', 'Azerbaijani Manat'), ('BAD', 'Bosnia-Herzegovina Dinar (1992–1994)'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BAN', 'Bosnia-Herzegovina New Dinar (1994–1997)'), ('BBD', 'Barbadian Dollar'), ('BDT', 'Bangladeshi Taka'), ('BEC', 'Belgian Franc (convertible)'), ('BEF', 'Belgian Franc'), ('BEL', 'Belgian Franc (financial)'), ('BGL', 'Bulgarian Hard Lev'), ('BGM', 'Bulgarian Socialist Lev'), ('BGN', 'Bulgarian Lev'), ('BGO', 'Bulgarian Lev (1879–1952)'), ('BHD', 'Bahraini Dinar'), ('BIF', 'Burundian Franc'), ('BMD', 'Bermudan Dollar'), ('BND', 'Brunei Dollar'), ('BOB', 'Bolivian Boliviano'), ('BOL', 'Bolivian Boliviano (1863–1963)'), ('BOP', 'Bolivian Peso'), ('BOV', 'Bolivian Mvdol'), ('BRB', 'Brazilian New Cruzeiro (1967–1986)'), ('BRC', 'Brazilian Cruzado (1986–1989)'), ('BRE', 'Brazilian Cruzeiro (1990–1993)'), ('BRL', 'Brazilian Real'), ('BRN', 'Brazilian New Cruzado (1989–1990)'), ('BRR', 'Brazilian Cruzeiro (1993–1994)'), ('BRZ', 'Brazilian Cruzeiro (1942–1967)'), ('BSD', 'Bahamian Dollar'), ('BTN', 'Bhutanese Ngultrum'), ('BUK', 'Burmese Kyat'), ('BWP', 'Botswanan Pula'), ('BYB', 'Belarusian Ruble (1994–1999)'), ('BYN', 'Belarusian Ruble'), ('BYR', 'Belarusian Ruble (2000–2016)'), ('BZD', 'Belize Dollar'), ('CAD', 'Canadian Dollar'), ('CDF', 'Congolese Franc'), ('CHE', 'WIR Euro'), ('CHF', 'Swiss Franc'), ('CHW', 'WIR Franc'), ('CLE', 'Chilean Escudo'), ('CLF', 'Chilean Unit of Account (UF)'), ('CLP', 'Chilean Peso'), ('CNH', 'Chinese Yuan (offshore)'), ('CNX', 'Chinese People’s Bank Dollar'), ('CNY', 'Chinese Yuan'), ('COP', 'Colombian Peso'), ('COU', 'Colombian Real Value Unit'), ('CRC', 'Costa Rican Colón'), ('CSD', 'Serbian Dinar (2002–2006)'), ('CSK', 'Czechoslovak Hard Koruna'), ('CUC', 'Cuban Convertible Peso'), ('CUP', 'Cuban Peso'), ('CVE', 'Cape Verdean Escudo'), ('CYP', 'Cypriot Pound'), ('CZK', 'Czech Koruna'), ('DDM', 'East German Mark'), ('DEM', 'German Mark'), ('DJF', 'Djiboutian Franc'), ('DKK', 'Danish Krone'), ('DOP', 'Dominican Peso'), ('DZD', 'Algerian Dinar'), ('ECS', 'Ecuadorian Sucre'), ('ECV', 'Ecuadorian Unit of Constant Value'), ('EEK', 'Estonian Kroon'), ('EGP', 'Egyptian Pound'), ('ERN', 'Eritrean Nakfa'), ('ESA', 'Spanish Peseta (A account)'), ('ESB', 'Spanish Peseta (convertible account)'), ('ESP', 'Spanish Peseta'), ('ETB', 'Ethiopian Birr'), ('EUR', 'Euro'), ('FIM', 'Finnish Markka'), ('FJD', 'Fijian Dollar'), ('FKP', 'Falkland Islands Pound'), ('FRF', 'French Franc'), ('GBP', 'British Pound'), ('GEK', 'Georgian Kupon Larit'), ('GEL', 'Georgian Lari'), ('GHC', 'Ghanaian Cedi (1979–2007)'), ('GHS', 'Ghanaian Cedi'), ('GIP', 'Gibraltar Pound'), ('GMD', 'Gambian Dalasi'), ('GNF', 'Guinean Franc'), ('GNS', 'Guinean Syli'), ('GQE', 'Equatorial Guinean Ekwele'), ('GRD', 'Greek Drachma'), ('GTQ', 'Guatemalan Quetzal'), ('GWE', 'Portuguese Guinea Escudo'), ('GWP', 'Guinea-Bissau Peso'), ('GYD', 'Guyanaese Dollar'), ('HKD', 'Hong Kong Dollar'), ('HNL', 'Honduran Lempira'), ('HRD', 'Croatian Dinar'), ('HRK', 'Croatian Kuna'), ('HTG', 'Haitian Gourde'), ('HUF', 'Hungarian Forint'), ('IDR', 'Indonesian Rupiah'), ('IEP', 'Irish Pound'), ('ILP', 'Israeli Pound'), ('ILR', 'Israeli Shekel (1980–1985)'), ('ILS', 'Israeli New Shekel'), ('INR', 'Indian Rupee'), ('IQD', 'Iraqi Dinar'), ('IRR', 'Iranian Rial'), ('ISJ', 'Icelandic Króna (1918–1981)'), ('ISK', 'Icelandic Króna'), ('ITL', 'Italian Lira'), ('JMD', 'Jamaican Dollar'), ('JOD', 'Jordanian Dinar'), ('JPY', 'Japanese Yen'), ('KES', 'Kenyan Shilling'), ('KGS', 'Kyrgystani Som'), ('KHR', 'Cambodian Riel'), ('KMF', 'Comorian Franc'), ('KPW', 'North Korean Won'), ('KRH', 'South Korean Hwan (1953–1962)'), ('KRO', 'South Korean Won (1945–1953)'), ('KRW', 'South Korean Won'), ('KWD', 'Kuwaiti Dinar'), ('KYD', 'Cayman Islands Dollar'), ('KZT', 'Kazakhstani Tenge'), ('LAK', 'Laotian Kip'), ('LBP', 'Lebanese Pound'), ('LKR', 'Sri Lankan Rupee'), ('LRD', 'Liberian Dollar'), ('LSL', 'Lesotho Loti'), ('LTL', 'Lithuanian Litas'), ('LTT', 'Lithuanian Talonas'), ('LUC', 'Luxembourgian Convertible Franc'), ('LUF', 'Luxembourgian Franc'), ('LUL', 'Luxembourg Financial Franc'), ('LVL', 'Latvian Lats'), ('LVR', 'Latvian Ruble'), ('LYD', 'Libyan Dinar'), ('MAD', 'Moroccan Dirham'), ('MAF', 'Moroccan Franc'), ('MCF', 'Monegasque Franc'), ('MDC', 'Moldovan Cupon'), ('MDL', 'Moldovan Leu'), ('MGA', 'Malagasy Ariary'), ('MGF', 'Malagasy Franc'), ('MKD', 'Macedonian Denar'), ('MKN', 'Macedonian Denar (1992–1993)'), ('MLF', 'Malian Franc'), ('MMK', 'Myanmar Kyat'), ('MNT', 'Mongolian Tugrik'), ('MOP', 'Macanese Pataca'), ('MRO', 'Mauritanian Ouguiya (1973–2017)'), ('MRU', 'Mauritanian Ouguiya'), ('MTL', 'Maltese Lira'), ('MTP', 'Maltese Pound'), ('MUR', 'Mauritian Rupee'), ('MVP', 'Maldivian Rupee (1947–1981)'), ('MVR', 'Maldivian Rufiyaa'), ('MWK', 'Malawian Kwacha'), ('MXN', 'Mexican Peso'), ('MXP', 'Mexican Silver Peso (1861–1992)'), ('MXV', 'Mexican Investment Unit'), ('MYR', 'Malaysian Ringgit'), ('MZE', 'Mozambican Escudo'), ('MZM', 'Mozambican Metical (1980–2006)'), ('MZN', 'Mozambican Metical'), ('NAD', 'Namibian Dollar'), ('NGN', 'Nigerian Naira'), ('NIC', 'Nicaraguan Córdoba (1988–1991)'), ('NIO', 'Nicaraguan Córdoba'), ('NLG', 'Dutch Guilder'), ('NOK', 'Norwegian Krone'), ('NPR', 'Nepalese Rupee'), ('NZD', 'New Zealand Dollar'), ('OMR', 'Omani Rial'), ('PAB', 'Panamanian Balboa'), ('PEI', 'Peruvian Inti'), ('PEN', 'Peruvian Sol'), ('PES', 'Peruvian Sol (1863–1965)'), ('PGK', 'Papua New Guinean Kina'), ('PHP', 'Philippine Peso'), ('PKR', 'Pakistani Rupee'), ('PLN', 'Polish Zloty'), ('PLZ', 'Polish Zloty (1950–1995)'), ('PTE', 'Portuguese Escudo'), ('PYG', 'Paraguayan Guarani'), ('QAR', 'Qatari Riyal'), ('RHD', 'Rhodesian Dollar'), ('ROL', 'Romanian Leu (1952–2006)'), ('RON', 'Romanian Leu'), ('RSD', 'Serbian Dinar'), ('RUB', 'Russian Ruble'), ('RUR', 'Russian Ruble (1991–1998)'), ('RWF', 'Rwandan Franc'), ('SAR', 'Saudi Riyal'), ('SBD', 'Solomon Islands Dollar'), ('SCR', 'Seychellois Rupee'), ('SDD', 'Sudanese Dinar (1992–2007)'), ('SDG', 'Sudanese Pound'), ('SDP', 'Sudanese Pound (1957–1998)'), ('SEK', 'Swedish Krona'), ('SGD', 'Singapore Dollar'), ('SHP', 'St. Helena Pound'), ('SIT', 'Slovenian Tolar'), ('SKK', 'Slovak Koruna'), ('SLE', 'Sierra Leonean Leone'), ('SLL', 'Sierra Leonean Leone (1964—2022)'), ('SOS', 'Somali Shilling'), ('SRD', 'Surinamese Dollar'), ('SRG', 'Surinamese Guilder'), ('SSP', 'South Sudanese Pound'), ('STD', 'São Tomé & Príncipe Dobra (1977–2017)'), ('STN', 'São Tomé & Príncipe Dobra'), ('SUR', 'Soviet Rouble'), ('SVC', 'Salvadoran Colón'), ('SYP', 'Syrian Pound'), ('SZL', 'Swazi Lilangeni'), ('THB', 'Thai Baht'), ('TJR', 'Tajikistani Ruble'), ('TJS', 'Tajikistani Somoni'), ('TMM', 'Turkmenistani Manat (1993–2009)'), ('TMT', 'Turkmenistani Manat'), ('TND', 'Tunisian Dinar'), ('TOP', 'Tongan Paʻanga'), ('TPE', 'Timorese Escudo'), ('TRL', 'Turkish Lira (1922–2005)'), ('TRY', 'Turkish Lira'), ('TTD', 'Trinidad & Tobago Dollar'), ('TWD', 'New Taiwan Dollar'), ('TZS', 'Tanzanian Shilling'), ('UAH', 'Ukrainian Hryvnia'), ('UAK', 'Ukrainian Karbovanets'), ('UGS', 'Ugandan Shilling (1966–1987)'), ('UGX', 'Ugandan Shilling'), ('USD', 'US Dollar'), ('USN', 'US Dollar (Next day)'), ('USS', 'US Dollar (Same day)'), ('UYI', 'Uruguayan Peso (Indexed Units)'), ('UYP', 'Uruguayan Peso (1975–1993)'), ('UYU', 'Uruguayan Peso'), ('UYW', 'Uruguayan Nominal Wage Index Unit'), ('UZS', 'Uzbekistani Som'), ('VEB', 'Venezuelan Bolívar (1871–2008)'), ('VED', 'Bolívar Soberano'), ('VEF', 'Venezuelan Bolívar (2008–2018)'), ('VES', 'Venezuelan Bolívar'), ('VND', 'Vietnamese Dong'), ('VNN', 'Vietnamese Dong (1978–1985)'), ('VUV', 'Vanuatu Vatu'), ('WST', 'Samoan Tala'), ('XAF', 'Central African CFA Franc'), ('XAG', 'Silver'), ('XAU', 'Gold'), ('XBA', 'European Composite Unit'), ('XBB', 'European Monetary Unit'), ('XBC', 'European Unit of Account (XBC)'), ('XBD', 'European Unit of Account (XBD)'), ('XCD', 'East Caribbean Dollar'), ('XCG', 'Caribbean guilder'), ('XDR', 'Special Drawing Rights'), ('XEU', 'European Currency Unit'), ('XFO', 'French Gold Franc'), ('XFU', 'French UIC-Franc'), ('XOF', 'West African CFA Franc'), ('XPD', 'Palladium'), ('XPF', 'CFP Franc'), ('XPT', 'Platinum'), ('XRE', 'RINET Funds'), ('XSU', 'Sucre'), ('XTS', 'Testing Currency Code'), ('XUA', 'ADB Unit of Account'), ('XXX', 'Unknown Currency'), ('YDD', 'Yemeni Dinar'), ('YER', 'Yemeni Rial'), ('YUD', 'Yugoslavian Hard Dinar (1966–1990)'), ('YUM', 'Yugoslavian New Dinar (1994–2002)'), ('YUN', 'Yugoslavian Convertible Dinar (1990–1992)'), ('YUR', 'Yugoslavian Reformed Dinar (1992–1993)'), ('ZAL', 'South African Rand (financial)'), ('ZAR', 'South African Rand'), ('ZMK', 'Zambian Kwacha (1968–2012)'), ('ZMW', 'Zambian Kwacha'), ('ZRN', 'Zairean New Zaire (1993–1998)'), ('ZRZ', 'Zairean Zaire (1971–1993)'), ('ZWD', 'Zimbabwean Dollar (1980–2008)'), ('ZWG', 'Zimbabwean Gold'), ('ZWL', 'Zimbabwean Dollar (2009–2024)'), ('ZWR', 'Zimbabwean Dollar (2008)')], default='EUR', help_text='Currency used for transactions in this Hub', max_length=3)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for this Hub (e.g., Europe/Madrid, America/New_York)', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='System language for this Hub', max_length=10)),
                ('color_theme', models.CharField(choices=[('default', 'Default (Gray)'), ('blue', 'Blue')], default='default', max_length=20)),
                ('theme', models.CharField(choices=[('system', 'System (auto)'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10)),
                ('dark_mode', models.BooleanField(default=False)),
                ('dark_mode_auto', models.BooleanField(default=True)),
                ('auto_print', models.BooleanField(default=False)),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code (e.g., ES, FR, US)', max_length=2)),
                ('business_sector', models.CharField(blank=True, default='', help_text='Selected sector code (e.g., "hosteleria", "retail")', max_length=50)),
                ('selected_business_types', models.JSONField(blank=True, default=list, help_text='List of selected business type codes (e.g., ["bar", "restaurante"])')),
                ('selected_transversals', models.JSONField(blank=True, default=list, help_text='List of selected transversal model codes (e.g., ["multi_store", "franchise"])')),
                ('blueprint_version', models.CharField(blank=True, default='', help_text='Version of the blueprint data used during setup', max_length=20)),
                ('bridge_enabled', models.BooleanField(default=False, help_text='Master switch: enable/disable native bridge connection')),
                ('bridge_port', models.IntegerField(default=12321, help_text='WebSocket port for the native hardware bridge')),
                ('bridge_auto_print', models.BooleanField(default=True, help_text='Auto-print via bridge (if False, shows print preview in browser)')),
                ('allow_satellite_printing', models.BooleanField(default=False, help_text='Allow satellite terminals to print via the main terminal bridge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hub Configuration',
                'verbose_name_plural': 'Hub Configuration',
                'db_table': 'core_hubconfig',
            },
            bases=(apps.configuration.models.SingletonConfigMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_printer_id', models.CharField(help_text='Unique printer ID from the bridge (e.g., usb:0x04b8:0x0202)', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Display name for this printer', max_length=255)),
                ('printer_type', models.CharField(choices=[('usb', 'USB'), ('network', 'Network'), ('bluetooth', 'Bluetooth')], default='usb', max_length=50)),
                ('paper_width', models.IntegerField(default=80, help_text='Paper width in mm (58 or 80)')),
                ('document_types', models.JSONField(blank=True, default=list, help_text='Document types this printer handles (e.g., ["receipt", "kitchen_order"])')),
                ('priority', models.IntegerField(default=1, help_text='Priority for document routing (lower = higher priority)')),
                ('is_default', models.BooleanField(default=False, help_text='Use as fallback when no specific printer is configured for a document type')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive printers are ignored for routing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
                'db_table': 'core_printerconfig',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', help_text='Machine-readable code for blueprint mapping (e.g., general, reduced, super_reduced, exempt)', max_length=50, verbose_name='Code')),
                ('name', models.CharField(help_text='Display name for this tax class (e.g., "General 21%")', max_length=100, verbose_name='Name')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 21.00 for 21%)', max_digits=5, verbose_name='Tax Rate (%)')),
                ('description', models.CharField(blank=True, help_text='Optional description or notes', max_length=255, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, help_text='Use this tax class as default for new products', verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tax classes are hidden from selection', verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first in lists', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Class',
                'verbose_name_plural': 'Tax Classes',
                'db_table': 'core_taxclass',
                'ordering': ['order', 'rate'],
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Tagline shown on login screen', max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='VAT/Tax ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL')),
                ('tiktok', models.URLField(blank=True, help_text='TikTok profile URL')),
                ('google_maps', models.URLField(blank=True, help_text='Google Maps link')),
                ('public_site_enabled', models.BooleanField(default=False, help_text='Enable public landing page at /public/')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate in percentage (e.g., 21.00 for 21%)', max_digits=5)),
                ('tax_included', models.BooleanField(default=True, help_text='Tax included in prices')),
                ('receipt_header', models.TextField(blank=True, help_text='Additional text to show at the top of receipts')),
                ('receipt_footer', models.TextField(blank=True, help_text='Additional text to show at the bottom of receipts')),
                ('is_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_tax_class', models.ForeignKey(blank=True, help_text='Default tax class for products without category tax assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_as_default', to='configuration.taxclass', verbose_name='Default Tax Class')),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
                'db_table': 'core_storeconfig',
            },
            bases=(apps.configuration.models.SingletonConfigMixin, models.Model),
        ),
    ]
