# Generated by Django 6.0.2 on 2026-03-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubconfig',
            name='selected_blocks',
        ),
        migrations.RemoveField(
            model_name='hubconfig',
            name='solution_name',
        ),
        migrations.RemoveField(
            model_name='hubconfig',
            name='solution_slug',
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='blueprint_version',
            field=models.CharField(blank=True, default='', help_text='Version of the blueprint data used during setup', max_length=20),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='business_sector',
            field=models.CharField(blank=True, default='', help_text='Selected sector code (e.g., "hosteleria", "retail")', max_length=50),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='selected_business_types',
            field=models.JSONField(blank=True, default=list, help_text='List of selected business type codes (e.g., ["bar", "restaurante"])'),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='selected_transversals',
            field=models.JSONField(blank=True, default=list, help_text='List of selected transversal model codes (e.g., ["multi_store", "franchise"])'),
        ),
    ]
