# Generated by Django 5.2.8 on 2025-11-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='cloud_public_key',
            field=models.TextField(blank=True, help_text='Cloud RSA public key for validating command JWTs'),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='hub_jwt',
            field=models.TextField(blank=True, help_text='JWT token for Hub-to-Cloud authentication (RS256, 1 year)'),
        ),
        migrations.AlterField(
            model_name='hubconfig',
            name='cloud_api_token',
            field=models.CharField(blank=True, help_text='Legacy token (deprecated, use hub_jwt instead)', max_length=255),
        ),
    ]
