# Generated by Django 6.0.1 on 2026-02-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_printer_id', models.CharField(help_text='Unique printer ID from the bridge (e.g., usb:0x04b8:0x0202)', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Display name for this printer', max_length=255)),
                ('printer_type', models.CharField(choices=[('usb', 'USB'), ('network', 'Network'), ('bluetooth', 'Bluetooth')], default='usb', max_length=50)),
                ('paper_width', models.IntegerField(default=80, help_text='Paper width in mm (58 or 80)')),
                ('document_types', models.JSONField(blank=True, default=list, help_text='Document types this printer handles (e.g., ["receipt", "kitchen_order"])')),
                ('priority', models.IntegerField(default=1, help_text='Priority for document routing (lower = higher priority)')),
                ('is_default', models.BooleanField(default=False, help_text='Use as fallback when no specific printer is configured for a document type')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive printers are ignored for routing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
                'db_table': 'core_printerconfig',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='allow_satellite_printing',
            field=models.BooleanField(default=False, help_text='Allow satellite terminals to print via the main terminal bridge'),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='bridge_auto_print',
            field=models.BooleanField(default=True, help_text='Auto-print via bridge (if False, shows print preview in browser)'),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='bridge_port',
            field=models.IntegerField(default=12321, help_text='WebSocket port for the native hardware bridge'),
        ),
    ]
