# Generated by Django 5.2.7 on 2025-11-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubconfig',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('MXN', 'Mexican Peso ($)'), ('CAD', 'Canadian Dollar ($)'), ('AUD', 'Australian Dollar ($)'), ('BRL', 'Brazilian Real (R$)'), ('ARS', 'Argentine Peso ($)'), ('COP', 'Colombian Peso ($)'), ('CLP', 'Chilean Peso ($)'), ('PEN', 'Peruvian Sol (S/)'), ('CRC', 'Costa Rican Colón (₡)')], default='USD', help_text='Currency used for transactions in this Hub', max_length=3),
        ),
    ]
