# Generated by Django 5.2.8 on 2025-11-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_hubconfig_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubconfig',
            name='tunnel_port',
        ),
        migrations.RemoveField(
            model_name='hubconfig',
            name='tunnel_token',
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='cloud_api_token',
            field=models.CharField(blank=True, help_text='Token for authenticating HTTP requests to Cloud API', max_length=255),
        ),
    ]
