# Generated by Django 6.0.1 on 2026-02-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_add_printerconfig_and_bridge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='bridge_enabled',
            field=models.BooleanField(default=False, help_text='Master switch: enable/disable native bridge connection'),
        ),
    ]
