# Generated by Django 6.0.2 on 2026-03-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_storeconfig_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='show_modules_in_sidebar',
            field=models.BooleanField(default=False, help_text='Show installed modules in the sidebar navigation'),
        ),
        migrations.AlterField(
            model_name='storeconfig',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Operating hours per weekday. Format: {"mon": {"open": "09:00", "close": "22:00"}, ...}. Days without entries are considered closed.'),
        ),
    ]
