# Generated by Django 6.0.1 on 2026-02-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_bridge_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='solution_name',
            field=models.CharField(blank=True, default='', help_text='Selected solution display name (e.g., Salon & Spa)', max_length=200),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='solution_slug',
            field=models.CharField(blank=True, default='', help_text='Selected solution slug from Cloud (e.g., salon-pos)', max_length=100),
        ),
    ]
