# Generated by Django 5.2.8 on 2025-12-19 20:49

import apps.configuration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_add_dark_mode_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable automatic backups')),
                ('frequency', models.CharField(choices=[('disabled', 'Disabled'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often to run backups', max_length=20)),
                ('time_hour', models.PositiveSmallIntegerField(default=3, help_text='Hour to run backup (0-23, default 3 AM)')),
                ('time_minute', models.PositiveSmallIntegerField(default=0, help_text='Minute to run backup (0-59)')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Days to keep backups (0 = keep forever)')),
                ('max_backups', models.PositiveIntegerField(default=10, help_text='Maximum number of backups to keep (0 = unlimited)')),
                ('last_backup_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful backup', null=True)),
                ('last_backup_size', models.PositiveIntegerField(default=0, help_text='Size of last backup in bytes')),
                ('last_backup_path', models.CharField(blank=True, help_text='Path/key of last backup', max_length=500)),
                ('last_error', models.TextField(blank=True, help_text='Last backup error message (empty if successful)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configuration',
                'db_table': 'core_backupconfig',
            },
            bases=(apps.configuration.models.SingletonConfigMixin, models.Model),
        ),
    ]
