# Generated by Django 6.0.1 on 2026-02-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_hubconfig_solution_name_hubconfig_solution_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code (e.g., ES, FR, US)', max_length=2),
        ),
    ]
