# Generated by Django 6.0 on 2025-12-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_backup_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this tax class (e.g., "General 21%")', max_length=100, verbose_name='Name')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 21.00 for 21%)', max_digits=5, verbose_name='Tax Rate (%)')),
                ('description', models.CharField(blank=True, help_text='Optional description or notes', max_length=255, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, help_text='Use this tax class as default for new products', verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tax classes are hidden from selection', verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first in lists', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Class',
                'verbose_name_plural': 'Tax Classes',
                'db_table': 'core_taxclass',
                'ordering': ['order', 'rate'],
            },
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='default_tax_class',
            field=models.ForeignKey(blank=True, help_text='Default tax class for products without category tax assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_as_default', to='configuration.taxclass', verbose_name='Default Tax Class'),
        ),
    ]
