# Generated by Django 6.0 on 2025-12-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_add_taxclass_and_default_tax_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='System language for this Hub', max_length=10),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Timezone for this Hub (e.g., Europe/Madrid, America/New_York)', max_length=50),
        ),
    ]
