# Generated by Django 5.2.8 on 2026-01-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_add_timezone_language_to_hubconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='hub_refresh_token',
            field=models.TextField(blank=True, help_text='Refresh token for Hub JWT (RS256, 2 years)'),
        ),
    ]
