# Generated by Django 6.0.1 on 2026-02-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_update_currency_choices_to_babel'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='tagline',
            field=models.CharField(blank=True, help_text='Tagline shown on login screen', max_length=255),
        ),
    ]
