# Generated by Django 6.0.1 on 2026-02-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_add_tagline_to_storeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='theme',
            field=models.CharField(choices=[('system', 'System (auto)'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10),
        ),
        migrations.AlterField(
            model_name='hubconfig',
            name='dark_mode_auto',
            field=models.BooleanField(default=True),
        ),
    ]
