# Generated by Django 6.0.2 on 2026-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_add_theme_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubconfig',
            name='cloud_api_token',
            field=models.TextField(blank=True, help_text='Legacy token (deprecated, use hub_jwt instead)'),
        ),
    ]
