CREATE TABLE IF NOT EXISTS w2612d_holds (
    id TEXT PRIMARY KEY, hub_id TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_w2612d_holds_hub ON w2612d_holds (hub_id);
CREATE TABLE IF NOT EXISTS w2612d_sweeps (
    hub_id TEXT PRIMARY KEY, last_sweep TEXT NOT NULL);
