// The version of this SDK, readable from a COMPILED bundle — ERPlora/hub#1236.
//
// A module ships `dist/<id>.esm.js`, built and committed on the developer's machine and published
// as-is. Before this constant existed, nothing in that bundle said which `@erplora/module-sdk` it
// had been compiled against: the package was `private: true, version "0.0.0"` and the 24 module
// repos declared it `workspace:*`, so the honest answer was "whatever checkout of the hub the
// developer had open". This is the same seal `dist/outfitkit.json` puts on the other half of the
// build (hub#1024).
//
// 🔴 NOT re-exported from `src/index.ts`, on purpose. `contracts/kernel/sdk.d.ts` is the FROZEN
// public surface of this package (ADR «El Hub se CIERRA como KERNEL»), generated by `tsc` from
// `src/index.ts` and mirrored byte for byte in `ERPlora/module-toolkit`. Hanging a constant off
// the entry point would move that surface — and a version number is not part of the API a module
// is written against. Import it by path when a build needs to stamp it:
//
//     import { SDK_VERSION } from '@erplora/module-sdk/src/version.ts';
//
// The number is written by `scripts/stamp-version.sh`, which the release
// (`.github/workflows/build-hub.yml`) runs with the version of the `v*` tag — the SAME number the
// image, the Rust crates and the npm package get. In the committed tree it is the workspace's
// "in development" value, and `scripts/tests/publish-sdks.test.sh` fails if the three disagree.
export const SDK_VERSION = '1.0.0';
