CREATE TABLE IF NOT EXISTS p1701_order (
  id TEXT PRIMARY KEY,
  hub_id TEXT NOT NULL,
  discount_percent NUMERIC NOT NULL DEFAULT 0,
  channel TEXT NOT NULL DEFAULT '',
  closed INTEGER NOT NULL DEFAULT 0,
  tip_percent NUMERIC NOT NULL DEFAULT 0
);
