# Generated by Django 5.2.8 on 2025-12-16 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_access_token', models.TextField(blank=True)),
                ('jwt_refresh_token', models.TextField(blank=True)),
                ('jwt_cached_at', models.DateTimeField(blank=True, null=True)),
                ('rsa_public_key', models.TextField(blank=True)),
                ('public_key_cached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Cache',
                'verbose_name_plural': 'Token Cache',
                'db_table': 'sync_tokencache',
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('operation_type', models.CharField(choices=[('user_register', 'Register User'), ('user_remove', 'Remove User'), ('user_update', 'Update User'), ('plugin_install', 'Plugin Install'), ('plugin_uninstall', 'Plugin Uninstall'), ('sale_sync', 'Sale Sync')], max_length=50)),
                ('endpoint', models.CharField(help_text='API endpoint to call', max_length=500)),
                ('method', models.CharField(default='POST', help_text='HTTP method', max_length=10)),
                ('payload', models.JSONField(default=dict, help_text='Request body')),
                ('headers', models.JSONField(default=dict, help_text='Additional headers')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('last_error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync Queue Item',
                'verbose_name_plural': 'Sync Queue',
                'db_table': 'sync_syncqueue',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['hub_id', 'status', 'next_retry_at'], name='sync_syncqu_hub_id_66521c_idx'), models.Index(fields=['hub_id', 'operation_type', 'status'], name='sync_syncqu_hub_id_4257f9_idx')],
            },
        ),
    ]
