# Generated by Django 6.0 on 2025-12-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncqueue',
            name='operation_type',
            field=models.CharField(choices=[('user_register', 'Register User'), ('user_remove', 'Remove User'), ('user_update', 'Update User'), ('module_install', 'Module Install'), ('module_uninstall', 'Module Uninstall'), ('sale_sync', 'Sale Sync')], max_length=50),
        ),
    ]
