# Generated by Django 5.2.7 on 2025-11-11 16:40
# Modified to skip database operations - indexes already exist with correct names

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        # No database operations needed - table and indexes already exist
        # This migration only updates Django's state to match the new app structure
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='syncqueue',
                    new_name='core_syncqu_status_0189d1_idx',
                    old_name='core_syncqu_status_6f8e25_idx',
                ),
                migrations.RenameIndex(
                    model_name='syncqueue',
                    new_name='core_syncqu_operati_a04ea8_idx',
                    old_name='core_syncqu_operati_f2c3e6_idx',
                ),
            ],
        ),
    ]
