CREATE TABLE IF NOT EXISTS crm_note (id TEXT PRIMARY KEY, hub_id TEXT NOT NULL, created_by TEXT NOT NULL, customer_id TEXT NOT NULL DEFAULT '', text TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS crm_counter (name TEXT PRIMARY KEY, n INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS crm_receipt (id TEXT PRIMARY KEY, hub_id TEXT NOT NULL, issuer TEXT NOT NULL);