CREATE TABLE IF NOT EXISTS agenda_slot (id TEXT PRIMARY KEY, hub_id TEXT NOT NULL, starts_at TEXT NOT NULL, minutes INTEGER NOT NULL DEFAULT 30);
CREATE TABLE IF NOT EXISTS agenda_booking (id TEXT PRIMARY KEY, hub_id TEXT NOT NULL, created_by TEXT NOT NULL DEFAULT '', customer TEXT NOT NULL DEFAULT '', starts_at TEXT NOT NULL DEFAULT '', minutes INTEGER NOT NULL DEFAULT 30);
